= ログ検索クエリ構文
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Monitoring ログ検索では、クエリビルダーとファセット検索ユーザインターフェースを使用するだけでなく、ログ検索クエリ言語を使用できます。

== 検索語

検索語は語と演算子で構成されます。検索語は単一語 ("hello" など) にすることも、語句 ("hello dolly" など) にすることもできます。 

複数の語を Boolean 演算子で組み合わせて複雑なクエリを作成できます。 

== 語の修飾

ログ検索クエリ言語を使用してクエリ語を修飾し、幅広い検索オプションを提供できます。

== ワイルドカード検索

単一語の中の 1 文字および複数文字のワイルドカード検索を使用できます。

[NOTE]
語句クエリ内ではワイルドカード検索を使用できません。

1 文字のワイルドカード検索を実行するには、​`?`​ 記号を使用します。1 文字のワイルドカード検索では、語の 1 文字を ​`?`​ で代替して一致する語を検索します。たとえば、"text" または "test" を検索する場合は、次の検索を使用できます。

​`te?t`​

複数文字のワイルドカード検索を実行するには、* 記号を使用します。複数文字のワイルドカード検索では、0 文字以上を代替して検索します。たとえば、test、tests、または tester を検索するには、次の検索を使用します。

​`test*`​

​`te*t`​ のように、語の中間でワイルドカード検索を使用することもできます。

[NOTE]
検索の最初の文字として * または ​`?`​ 記号を使用することはできません。

== ファジー検索

単語の末尾にチルダ (&#126;) 記号を使用して、ファジー検索を実行できます。たとえば、スペルが "roam" と似ている語を検索するには、次のファジー検索を使用できます。

​`roam&#759;`​

この検索では、foam や roams などの語が返されます。

== Boolean 演算子

Boolean 演算子では、語を論理演算子で組み合わせることができます。ログ検索クエリ言語では、Boolean 演算子として ​`AND`​、​`+`​、​`OR`​、​`NOT`​、​`-`​ をサポートしています。

[NOTE]
Boolean 演算子はすべて大文字にする必要があります。


[%header%autowidth.spread,cols="a,a,a"]
|===
|Boolean 演算子|説明|例
|​`AND`​     |​`AND`​ 演算子は、1 つのドキュメントのテキスト内の任意の場所に両方の語が存在するドキュメントを照合します。これは、共通集合と同じです。単語 ​`AND`​ を記号 ​`&&`​ で置き換えることができます。.|"anypoint monitoring" が含まれるドキュメントを検索するには、次のクエリを使用します。
​`"anypoint monitoring" AND "results"`​
|​`OR`​      |​`OR`​ 演算子は、2 つの語の間に Boolean 演算子が挿入されていない場合にデフォルトで使用されます。​`OR`​ 演算子は 2 つの語を関連付け、いずれかの語がドキュメントに存在すれば、一致ドキュメントを返します。これは、和集合と同じです。記号 ​`&#124; &#124;`​ を単語 ​`OR`​ の代わりに使用できます。.|"monitoring anypoint" または "monitoring" だけが含まれるドキュメントを検索するには、次のクエリを使用します。

​`"monitoring anypoint" monitoring`​

または

​`"monitoring anypoint" OR monitoring`​
|​`NOT`​| ​`NOT`​ 演算子は、​`NOT`​ の後に語が含まれるドキュメントを除外します。これは、差集合と同じです。記号 ​`!`​ を単語 ​`NOT`​ の代わりに使用できます。.|"anypoint monitoring" が含まれ、"functional" が含まれないドキュメントを検索するには、次のクエリを使用します。
​`"anypoint monitoring" NOT "functional"`​ +
[NOTE]
​`NOT`​ 演算子は、1 語だけの場合は使用できません。たとえば、次の検索では結果が返されません。 +
​`NOT "functional"`​
|​`+`​|​`+`​ 記号の後の語が 1 つのドキュメントの項目内の任意の場所に存在する必要があります。|"anypoint" は必ず含まれ、"monitoring" は含まれる可能性がある場合は、次のクエリを使用します。

​`+anypoint monitoring`​
|​`-`​|​`-`​ の後に語が含まれるドキュメントを除外します。|"anypoint monitoring"は含まれ、"results"は含まれないドキュメントを検索するには、次のクエリを使用します。 +

​`"anypoint monitoring" -"results"`​
|===


== 特殊文字

クエリ構文の一部として特殊文字をエスケープできます。現在サポートされている特殊文字のリストには、次の文字が含まれます。

​`+ - && || ! ( ) { } [ ] ^ " &#126; * ? : &#92; < >`​

これらの文字をエスケープするには、その文字の前に ​`\`​ を使用します。たとえば、(1+1):2 を検索するには、次のクエリを使用します。

​`\(1\+1\)\:2`​


== 検索項目

検索を実行するときには、項目名を指定するか、デフォルトを使用します。項目名とデフォルト項目は、検索実装に固有です。

項目名の後にコロン、検索する語を続けて入力して、任意の項目を検索します。
たとえば、ログ検索クエリ言語のインデックスに 2 つの項目 (application と message) があり、message がデフォルト項目だとします。テキスト "don't go this way" が含まれる "The Right Way" という結果を見つける場合は、次のように入力します。

​`message:"The Right Way" AND application:go`​

​`message`​ はデフォルト項目であるため、項目インジケータは不要です。






