= Anypoint Monitoring のログ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*https://www.mulesoft.com/anypoint-pricing[Titanium サブスクリプションが必要]*

​xref:runtime-manager::logs.adoc[Runtime Manager]​ を使用したログの記録に加え、Anypoint Monitoring を使用してログファイルを集約し、ログの管理、検索、絞り込み、分析を行うことができます。これらの機能では次の操作がサポートされます。

* 選択された Mule アプリケーションと環境の検索に基づいてイベントおよび情報パターンの比較分析と識別を行う。
* Mule アプリケーションの特定のワーカー (またはワーカーのセット) のログ内を検索して確認する問題の範囲を狭める。
* 重要なログのスナップショットを問題の原因に取り組む開発者と共有する。

​xref:logs-using.adoc[「ログの使用」]​を参照してください。

////
TODO _FUTURE?
WHAT ABOUT APIS?
////

//*TODO _FUTURE? |NEED STEPS & INFO ON APP NETWORK DIAGNOSTIC LOG SEARCH, BEHAVIOR WITH INSIGHTS?*
////
App network diagnostic log search |Limited, Singe App (base subscription) vs. Included for Premium Add on

Can we action on an alert from the portal, say retry or skip the transaction which generated the alert?Yes, transactions can be retried and skipped when Insights is turned on.
////

////
TODO _FUTURE? |NEED DESCRIPTIONS
* Log-based profiler?
* Thread and heap dump
////

////
TODO _FUTURE?
Log Designs
Logs supported actions
Logs filtering and facets
Logs filtering through content (interactive with hotspots)
Navigating within selected logs

Explorations
Logs filtering and facets explorations
////
