= カスタムダッシュボードとしての組み込みダッシュボードの保存
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

カスタムダッシュボードの作成を簡単にするために、Anypoint Monitoring のタブに含まれる組み込みダッシュボードをカスタムダッシュボードとして保存し、ニーズに合わせてカスタマイズできます。これにより、トラブルシューティング、アラートのセットアップ、ダッシュボード内の複数リソースの比較など、提供されている柔軟性と機能をカスタムダッシュボードで利用できます。 

組み込みダッシュボードをカスタムダッシュボードとして保存するには、次の手順に従います。 

. Anypoint Platform にサインインします。
. *[Anypoint Monitoring]* で、左のメニューから *[Built-in dashboards (組み込みダッシュボード)]* をクリックします。
. 保存する組み込みダッシュボードのタブをクリックします (*[Performance (パフォーマンス)]* など)。 
. *[Save as (別名で保存)]* アイコンをクリックします。 
. *[Save as (別名で保存)]* ダイアログで、​*[Name (名前)]* にカスタムダッシュボードの名前を入力し、​*[Save (保存)]* をクリックします。 +
[NOTE]
新しいカスタムダッシュボードの名前は一意にする必要があります。

緑の確認バナーが画面上部に表示されます。 
. 緑の確認バナー内の *[View in custom dashboards (カスタムダッシュボードで表示)]* リンクをクリックすると、新しいカスタムダッシュボードが入力した名前でカスタムダッシュボードのリストに表示されます。 +
バナーはしばらくすると消えます。バナーのリンクをクリックしなかった場合、左側のメニューで *[Custom dashboards (カスタムダッシュボード)]* クリックすると、カスタムダッシュボードのリストが表示されます。 +
これで、カスタムダッシュボードを設定できるようになりました。 

== 関連情報

xref:dashboard-custom-config.adoc[カスタムダッシュボードおよびチャートの設定]

